name: Schedule
on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn install

      - name: Run script
        run: |
          yarn start
        env:
          SMARTLINK_USERNAME: ${{ secrets.SMARTLINK_USERNAME }}
          SMARTLINK_PASSWORD: ${{ secrets.SMARTLINK_PASSWORD }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
